/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zbse20;

import java.util.UUID;

/**
 *
 * @author CONG HUY
 */
public class ConfigureNetwork extends java.awt.Dialog {

    /**
     * Creates new form ConfigureNetwork
     */
    public boolean isServer = true;
    public boolean isConnect = false;
    public String keyNumber="";
    public String host = "10.0.0.1";
    public ConfigureNetwork(java.awt.Frame parent, boolean modal, String Ip) {
        super(parent, modal);
        initComponents();
        uiHost.setText(Ip);
        UUID uuid = UUID.randomUUID();
        uikeyNumber.setText(uuid.toString());
    }

    private void SetUpNetwork() {
        // TODO add your handling code here:
        if(uiRadioServer.isSelected())
        {           
            isServer = true;
            isConnect = true;
        }
        else
        {           
           host  = uiHost.getText(); 
           isServer = false;
           isConnect = true;           
        }
        keyNumber = uikeyNumber.getText();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uiRadioServer = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        uibtRunTestScript = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uiHost = new javax.swing.JTextField();
        uibtRunTestScript2 = new javax.swing.JButton();
        uikeyNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Configure Network");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(uiRadioServer);
        uiRadioServer.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        uiRadioServer.setSelected(true);
        uiRadioServer.setText("Set up coordinator");
        uiRadioServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiRadioServerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton2.setText("Configure for Client side");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        uibtRunTestScript.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        uibtRunTestScript.setText("Connect");
        uibtRunTestScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uibtRunTestScriptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel1.setText("Enter host (example: CongKhanh or 192.168.1.12)");

        uiHost.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        uiHost.setEnabled(false);
        uiHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uiHostKeyPressed(evt);
            }
        });

        uibtRunTestScript2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        uibtRunTestScript2.setText("Cancel");
        uibtRunTestScript2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uibtRunTestScript2ActionPerformed(evt);
            }
        });

        uikeyNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        uikeyNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uikeyNumberKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel2.setText("Key Number:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(uiRadioServer)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(uiHost, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uikeyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(uibtRunTestScript, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uibtRunTestScript2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(uiRadioServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uiHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uikeyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uibtRunTestScript, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uibtRunTestScript2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void uibtRunTestScript2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uibtRunTestScript2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_uibtRunTestScript2ActionPerformed

    private void uiRadioServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiRadioServerActionPerformed
        // TODO add your handling code here:
       
        uiHost.setEnabled(false);
       // uikeyNumber.setEnabled(false);
        uiHost.setText(null);
        UUID uuid = UUID.randomUUID();
        uikeyNumber.setText(uuid.toString());
    }//GEN-LAST:event_uiRadioServerActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         uiHost.setEnabled(true);
         uikeyNumber.setText(null);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void uibtRunTestScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uibtRunTestScriptActionPerformed
        
        SetUpNetwork();
    }//GEN-LAST:event_uibtRunTestScriptActionPerformed

    private void uiHostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uiHostKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10)
            SetUpNetwork();
    }//GEN-LAST:event_uiHostKeyPressed

    private void uikeyNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uikeyNumberKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10)
            SetUpNetwork();
    }//GEN-LAST:event_uikeyNumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConfigureNetwork dialog = new ConfigureNetwork(new java.awt.Frame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField uiHost;
    private javax.swing.JRadioButton uiRadioServer;
    private javax.swing.JButton uibtRunTestScript;
    private javax.swing.JButton uibtRunTestScript2;
    private javax.swing.JTextField uikeyNumber;
    // End of variables declaration//GEN-END:variables
}
