/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zbse20;

import java.text.Normalizer;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author CONG HUY
 */
public class ConfigurationForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurationForm
     */
    public ConfigurationForm() {
        initComponents();
    }
    NTSMain Frm;
    public ConfigurationForm(NTSMain frm)
    {
        initComponents();
        Frm = frm;
        Reset();
    }
    
    public void Reset()
    {
        ConfigureFile config = Frm.getConfigureFile();
        if(config!=null)
        {
            if(jRadioButton1.getText().equals(config.ConfigureSystemService))
                jRadioButton1.setSelected(true);
            if(jRadioButton2.getText().equals(config.ConfigureSystemService))
                jRadioButton2.setSelected(true);
            if(jRadioButton3.getText().equals(config.ConfigureSystemService))
                jRadioButton3.setSelected(true);
            if(jRadioButton4.getText().equals(config.ConfigureSystemService))
                jRadioButton4.setSelected(true);
            
            if(jRadioButton5.getText().equals(config.ConfigureNetWorkProtocol))
                jRadioButton5.setSelected(true);
            if(jRadioButton6.getText().equals(config.ConfigureNetWorkProtocol))
                jRadioButton6.setSelected(true);
            if(jRadioButton7.getText().equals(config.ConfigureNetWorkProtocol))
                jRadioButton7.setSelected(true);
           
            jComboBox1.setSelectedItem(config.ConfigurSimulatiedDevice);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uibtGroup1 = new javax.swing.ButtonGroup();
        uibtGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        uibtClose = new javax.swing.JButton();
        uibtReset = new javax.swing.JButton();
        uibtOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure Networks");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configure System Services", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N

        uibtGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("NETWORK Access Server");
        jRadioButton1.setName("gr1"); // NOI18N

        uibtGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton2.setText("NETWORK Authenticate Server");
        jRadioButton2.setName("gr1"); // NOI18N

        uibtGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton3.setText("APPLICATION Trust Center");

        uibtGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton4.setText("ENERGY Services Interface");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configure Network Protocols", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 0, 12))); // NOI18N

        uibtGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("WI-FI");

        uibtGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton6.setText("HOMEPLUG");

        uibtGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jRadioButton7.setText("ZIGBEE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel1.setText("Configure Simulated Devices: ");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simulated IN PREMISE DISPLAY", "Simulated LOAD CONTROL DEVICE", "Simulated SMART THERMOSTAT", "Simulated METERING", "Simulated PREMISE ENERGY MGT", "Simulated PRE-PAYMENT TERMINAL", "Simulated INVERTER", "Simulated ELIECTRIC VEHICLE SPLY EQ", "Simulated END-USE MGNT DEVICE", "Simulated PLUG-IN ELECTRIC VEHICLE", "Simulated DISTRIBUTE ENERGY  RSCE", "Simulated MOMMS MODULE" }));

        uibtClose.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        uibtClose.setText("Close");
        uibtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uibtCloseActionPerformed(evt);
            }
        });

        uibtReset.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        uibtReset.setText("Reset");
        uibtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uibtResetActionPerformed(evt);
            }
        });

        uibtOk.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        uibtOk.setText("Ok");
        uibtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uibtOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(uibtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uibtReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uibtClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uibtClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uibtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uibtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uibtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uibtCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_uibtCloseActionPerformed

    private void uibtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uibtResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_uibtResetActionPerformed

    private void uibtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uibtOkActionPerformed
        // TODO add your handling code here:
        ConfigureFile config = Frm.getConfigureFile();
        if(jRadioButton1.isSelected())
            config.ConfigureSystemService = jRadioButton1.getText();
        if(jRadioButton2.isSelected())
            config.ConfigureSystemService = jRadioButton2.getText();
        if(jRadioButton3.isSelected())
            config.ConfigureSystemService = jRadioButton3.getText();
        if(jRadioButton4.isSelected())
            config.ConfigureSystemService = jRadioButton4.getText();
        if(jRadioButton5.isSelected())
            config.ConfigureNetWorkProtocol = jRadioButton5.getText();
        if(jRadioButton6.isSelected())
            config.ConfigureNetWorkProtocol = jRadioButton6.getText();
        if(jRadioButton7.isSelected())
            config.ConfigureNetWorkProtocol = jRadioButton7.getText();
        config.ConfigurSimulatiedDevice = jComboBox1.getSelectedItem().toString();
        Frm.setConfigureFile(config);
        this.setVisible(false);
    }//GEN-LAST:event_uibtOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConfigurationForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JButton uibtClose;
    private javax.swing.ButtonGroup uibtGroup1;
    private javax.swing.ButtonGroup uibtGroup2;
    private javax.swing.JButton uibtOk;
    private javax.swing.JButton uibtReset;
    // End of variables declaration//GEN-END:variables
}
